# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 20363477f1362bb1054487b1ec931f27770ddc36f50ae6221fce89bc561bf0e989ef5a01faa44cdba2185e73e2229faffa8cc2bbeef32748bb044385f5e92592

test:
  secret_key_base: 81311bfbf54727e9bf17f1b2fcac22199b69a7538bea0f3c958f2265d78a8cba04656e7fde86830be5f2dacdda31c39f44c61a6c2561513050b7fdcf4d59ac4b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
